-- db-design.md v4.2 §3.11-3.12. timeframe is strictly 1m/5m/15m/30m/60m —
-- BEFORE is never a timeframe value; pre_release_price is its own column
-- (Phase 2 instruction §4 "EventPriceReaction").

create table fx_prices (
  id bigint generated by default as identity primary key,
  fx_pair_id uuid not null references fx_pairs(id) on delete restrict,
  "timestamp" timestamptz not null,
  timeframe text not null check (timeframe in ('1m', '5m', '15m', '30m', '60m')),
  open numeric(12, 6) not null,
  high numeric(12, 6) not null,
  low numeric(12, 6) not null,
  close numeric(12, 6) not null,
  volume numeric,
  source text,
  created_at timestamptz not null default now(),
  unique (fx_pair_id, timeframe, "timestamp")
);

create index idx_fx_prices_pair_timestamp on fx_prices(fx_pair_id, "timestamp");
create index idx_fx_prices_pair_timeframe_timestamp on fx_prices(fx_pair_id, timeframe, "timestamp");

-- db-design.md v4.2 §3.12 (v4.2): max_upward_pips / max_downward_pips are
-- DB-stored (M-3 decision), computed and written by the Ingestion Worker
-- alongside pips, never recomputed by the API at response time.
create table event_price_reactions (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references economic_events(id) on delete restrict,
  fx_pair_id uuid not null references fx_pairs(id) on delete restrict,
  timeframe text not null check (timeframe in ('1m', '5m', '15m', '30m', '60m')),
  pre_release_price numeric(12, 6),
  post_release_price numeric(12, 6),
  movement numeric(12, 6),
  pips numeric(10, 2),
  change_percent numeric(10, 4),
  max_upward numeric(12, 6),
  max_downward numeric(12, 6),
  max_upward_pips numeric(10, 2),
  max_downward_pips numeric(10, 2),
  data_status text not null default 'PENDING' check (data_status in ('PENDING', 'AVAILABLE', 'UNAVAILABLE')),
  calculated_at timestamptz,
  created_at timestamptz not null default now(),
  unique (event_id, fx_pair_id, timeframe)
);

create index idx_event_price_reactions_event_id on event_price_reactions(event_id);
create index idx_event_price_reactions_fx_pair_id on event_price_reactions(fx_pair_id);
create index idx_event_price_reactions_event_pair_timeframe on event_price_reactions(event_id, fx_pair_id, timeframe);
