"""Assembles real narration audio from clips generated by hand in a phone
TTS app (オーナー確認 2026-08-07: 「ずんだボイス『ずんだもん読み上げアプリ』」
— App Store, https://apps.apple.com/jp/app/id6468403059、音声ファイルの保存・
共有が可能)。

This is the alternative to voicevox_narrate.py for an owner with no PC to
run the VOICEVOX engine on. Confirmed 2026-08-07: VOICEVOX has no iOS app,
and this cloud sandbox can't reach any hosted VOICEVOX-compatible API
either — voicevox.su-shiki.com, ondoku3.com, and api.tts.quest are all
blocked by this environment's network egress policy, the same block that
stops soundeffect-lab.info/dova-s.jp/otologic.jp/the YouTube CDN (see
docs/projects/moyasuka/voicevox-setup.mdのネットワーク制約に関する記載、
line-chat-ui.mdの効果音まわりの経緯も同じ理由)。

So instead of calling an API, this reads clips the owner already
generated and exported one line at a time from the phone app.

Workflow:

  1. Generate the recording checklist for a script:

         python3 -m moyasuka.manual_narration list \
             --script moyasuka/scripts/01-sample.md \
             --out /tmp/moyasuka-01-checklist.txt

     Lists every spoken line in order, each tagged with the exact
     filename it must be saved as (001.wav, 002.wav, ...). Lines with no
     narration (images, stickers, sfx cues) are skipped — nothing to
     record for those.

     With --format json instead, writes a machine-readable array
     ([{"index", "speaker_id", "speaker", "text"}, ...]) meant for the
     iPad Shortcuts automation described in
     docs/projects/moyasuka/voicevox-setup.md (方式A': Shortcuts自動化) —
     that Shortcut loops over this file and calls the WEB版VOICEVOX API
     (tts.quest / su-shiki.com) once per line, from the owner's iPad. This
     module itself never calls that API — this sandbox can't reach it
     either (see below) — it only produces the list the Shortcut consumes
     and, same as always, assembles whatever clips come back.

  2. Get each line synthesized and saved as {index:03d}.wav, either:

     a) In the phone app, work through the text checklist top to bottom:
        paste each line's text, pick the character's voice, synthesize,
        save/share the resulting file under exactly the name the
        checklist gives it. Put them all in one folder, then upload that
        folder (zip is fine) to the chat. (Fully manual, ~20-30 taps per
        video.)

     b) Or run the Shortcut built from the json checklist above — it
        loops through every line automatically via the WEB版VOICEVOX API
        and saves each clip with the right filename, no per-line manual
        work. See docs/projects/moyasuka/voicevox-setup.md for the setup
        and the capacity-management rule that comes with it (one video's
        clips must be uploaded before the next recording pass starts, or
        the Shortcut's self-cleanup step wipes them).

  3. Once the files land on disk here, assemble them:

         python3 -m moyasuka.manual_narration assemble \
             --script moyasuka/scripts/01-sample.md \
             --clips-dir /path/to/uploaded/clips \
             --out /tmp/moyasuka-01-narration

     Writes <out>.wav and <out>.durations.json — the exact same output
     shape voicevox_narrate.py produces, so from here the workflow is
     identical:

         python3 -m moyasuka.line_chat \
             --script moyasuka/scripts/01-sample.md \
             --audio /tmp/moyasuka-01-narration.wav \
             --durations /tmp/moyasuka-01-narration.durations.json \
             --out moyasuka-01-final.mp4

Any common audio extension (.wav/.mp3/.m4a/.aac/.ogg) is accepted and
auto-transcoded to wav before mixing, matching whatever the app exports.

Known open item: the app's voice roster comes from an in-app gacha, so
there's no guarantee all 5 cast roles (docs/projects/moyasuka/
content-backlog.md キャスト運用) are unlockable by name — if a script's
話者 doesn't have a matching unlocked voice yet, substitute the closest
available voice for that recording pass; getting the cast to line up
exactly is a manual judgment call each time, not something this script
can enforce.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from tempfile import TemporaryDirectory

from moyasuka.audio_mix import mix_clips_at_times, wav_duration
from moyasuka.line_chat import (
    IMAGE_VIEW_SECONDS,
    PAUSE_SECONDS,
    PHOTO_VIEW_SECONDS,
    STICKER_VIEW_SECONDS,
    estimate_arrivals,
    is_pause_only,
    parse_chat_script,
    timing_fingerprint,
    total_seconds_for,
)
from moyasuka.voicevox_narrate import CHARACTER_SPEAKER_IDS, DEFAULT_SPEAKER_ID

SUPPORTED_EXTS = (".wav", ".mp3", ".m4a", ".aac", ".ogg")


def _narration_items(items: list[dict]) -> list[int]:
    """Indices into `items` that need a recorded clip — spoken text lines
    only, not sfx cues, narration cards, images, stickers, or silent
    "......" pause beats (2026-08-14: those get a fixed silence instead of
    a recorded/synthesized clip, see line_chat.py's is_pause_only())."""
    return [
        i for i, item in enumerate(items)
        if item["type"] == "msg" and item.get("kind", "text") == "text"
        and not is_pause_only(item["text"])
    ]


def _speaker_id_for(speaker_name: str) -> int:
    speaker_id = CHARACTER_SPEAKER_IDS.get(speaker_name)
    if speaker_id is None:
        print(
            f"警告: 話者「{speaker_name}」の音声IDが未設定です。"
            f"ずんだもん(id={DEFAULT_SPEAKER_ID})で代用します。"
            f"voicevox_narrate.pyのCHARACTER_SPEAKER_IDSに追加してください。",
            file=sys.stderr,
        )
        return DEFAULT_SPEAKER_ID
    return speaker_id


def write_checklist(script_path: str, out_path: str, fmt: str = "text") -> int:
    """Writes the recording checklist. fmt="text" is the human-readable
    checklist for the phone-app manual workflow (default, unchanged from
    before). fmt="json" writes a machine-readable array intended for the
    iPad Shortcuts automation (docs/projects/moyasuka/voicevox-setup.md の
    「方式A': Shortcuts自動化」) to loop over and feed to the WEB版VOICEVOX
    API — each entry carries the resolved speaker_id so the Shortcut
    doesn't need its own copy of the casting table."""
    title, items = parse_chat_script(script_path)
    indices = _narration_items(items)

    if fmt == "json":
        records = []
        for i in indices:
            item = items[i]
            records.append({
                "index": i,
                "speaker_id": _speaker_id_for(item["speaker"]),
                "speaker": item["speaker"],
                "text": item["text"],
            })
        Path(out_path).write_text(
            json.dumps(records, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        return len(indices)

    lines = [f"台本: {title}", f"収録が必要なセリフ: {len(indices)}行", ""]
    for n, i in enumerate(indices, start=1):
        item = items[i]
        lines.append(f"[{n}/{len(indices)}] {i:03d}.wav  話者:{item['speaker']}  「{item['text']}」")
    Path(out_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(indices)


def _find_clip(clips_dir: Path, index: int) -> Path | None:
    # exact zero-padded match first (the convention used by the phone-app
    # manual workflow's checklist, e.g. "005.wav")
    for ext in SUPPORTED_EXTS:
        p = clips_dir / f"{index:03d}{ext}"
        if p.exists():
            return p
    # fall back to matching by numeric value regardless of zero-padding —
    # the iPad Shortcuts automation (方式A') builds filenames by string
    # concatenation inside the Shortcuts app, and Shortcuts has no built-in
    # "pad number to N digits" action (confirmed 2026-08-09 while building
    # it live with the owner — searched "文字"/"数字", nothing fit).
    # Rather than fight that in the Shortcuts UI, accept whatever width the
    # Shortcut actually produces ("5.wav", "05.wav", "005.wav", ...) as
    # long as the number matches — the padding was only ever cosmetic for
    # sort order, never load-bearing for correctness.
    for p in sorted(clips_dir.iterdir()):
        if not p.is_file() or p.suffix.lower() not in SUPPORTED_EXTS:
            continue
        try:
            if int(p.stem) == index:
                return p
        except ValueError:
            continue
    return None


def _to_wav(src: Path, dst: str) -> None:
    if src.suffix.lower() == ".wav":
        shutil.copyfile(src, dst)
        return
    subprocess.run(["ffmpeg", "-y", "-i", str(src), dst], check=True, capture_output=True)


def assemble(script_path: str, clips_dir: str, out_wav: str, out_durations_json: str) -> float:
    title, items = parse_chat_script(script_path)
    if not items:
        raise ValueError(f"no chat items found in {script_path}")
    clips_root = Path(clips_dir)

    durations: list[float] = []
    clip_paths: dict[int, str] = {}
    missing: list[int] = []

    with TemporaryDirectory() as tmp:
        for i, item in enumerate(items):
            if item["type"] == "sfx":
                durations.append(0.0)
                continue
            if item["type"] == "card":
                durations.append(1.2)
                continue
            kind = item.get("kind", "text")
            if kind == "image":
                durations.append(IMAGE_VIEW_SECONDS)
                continue
            if kind == "sticker":
                durations.append(STICKER_VIEW_SECONDS)
                continue
            if kind == "photo":
                durations.append(PHOTO_VIEW_SECONDS)
                continue
            if is_pause_only(item["text"]):
                durations.append(PAUSE_SECONDS)
                continue

            src = _find_clip(clips_root, i)
            if src is None:
                missing.append(i)
                durations.append(1.5)  # keeps the timeline sane if this runs anyway
                continue
            wav_path = f"{tmp}/clip_{i:03d}.wav"
            _to_wav(src, wav_path)
            durations.append(wav_duration(wav_path))
            clip_paths[i] = wav_path

        if missing:
            names = ", ".join(f"{i:03d}.*" for i in missing)
            raise SystemExit(
                f"{len(missing)}個のクリップが見つかりません({names})。"
                f"'python3 -m moyasuka.manual_narration list'で作ったチェックリストの"
                f"ファイル名どおりに{clips_dir}へ配置してください。"
            )

        arrivals = estimate_arrivals(items, durations)
        # shared with line_chat.render_video/gcp_tts_narrate.build_narration
        # — see total_seconds_for()'s docstring for why this must not be a
        # locally-duplicated `+ 1.2` (2026-08-18 incident).
        total_seconds = total_seconds_for(items, arrivals)
        mix_clips_at_times(clip_paths, arrivals, total_seconds, out_wav)

    with open(out_durations_json, "w", encoding="utf-8") as f:
        json.dump(durations, f, ensure_ascii=False)

    # see gcp_tts_narrate.build_narration's docstring / line_chat.
    # timing_fingerprint's docstring — same stale-audio hazard applies here
    Path(f"{out_durations_json}.timing").write_text(timing_fingerprint(), encoding="utf-8")

    return total_seconds


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Assemble real narration from手動 phone-app TTS clips.")
    sub = parser.add_subparsers(dest="mode", required=True)

    p_list = sub.add_parser("list", help="write the recording checklist for a script")
    p_list.add_argument("--script", required=True)
    p_list.add_argument("--out", required=True)
    p_list.add_argument(
        "--format", choices=["text", "json"], default="text",
        help="text = human-readable checklist for the phone-app manual workflow (default); "
             "json = machine-readable array for the iPad Shortcuts automation",
    )

    p_asm = sub.add_parser("assemble", help="assemble uploaded clips into narration audio")
    p_asm.add_argument("--script", required=True)
    p_asm.add_argument("--clips-dir", required=True)
    p_asm.add_argument("--out", required=True, help="output prefix — writes <out>.wav and <out>.durations.json")

    args = parser.parse_args(argv)

    if args.mode == "list":
        n = write_checklist(args.script, args.out, fmt=args.format)
        print(f"wrote {args.out} ({n}行, format={args.format})")
        return 0

    total = assemble(args.script, args.clips_dir, f"{args.out}.wav", f"{args.out}.durations.json")
    print(f"wrote {args.out}.wav / {args.out}.durations.json ({total:.1f}s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
